[package]
name = "eurochef-edb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.10.0"
num = "0.4"
serde = { version = "1", features = ["derive"] }